server:
  port: 8900

spring:
  application:
    name: consumer-order-ribbon

#user:
#  url: http://localhost:7900/user/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
  instance:
    instance-id: consumer-order-ribbon:8900
