spring:
  application:
    name: EUREKA-HA
  profiles:
    active: peer3
server:
  port: 8763

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/