server:
  port: 10900

spring:
  application:
    name: apigateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

zuul:
  routes:

#    provider-user: /abc/**
#  ignored-services: consumer-order

